In [1]:
#Write a NumPy program to get the numpy version and show numpy build configuration

In [2]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/hp/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/hp/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/hp/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/hp/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/hp/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/hp/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/hp/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/hp/anaconda3\\Library\\include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,S

In [3]:
#Write a NumPy program to get help on the add function.

In [5]:
import numpy as np
print(np.info(np.add))
#or we can use ?
np.add?


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [ ]:
#Write a NumPy program to swap rows and columns of a given array in reverse order

In [6]:
import numpy as np
nums = np.array([[[1, 2, 3, 4],
               [0, 1, 3, 4],
               [90, 91, 93, 94],
               [5, 0, 3, 2]]])

print(nums)
print(nums[::-1, ::-1])


[[[ 1  2  3  4]
  [ 0  1  3  4]
  [90 91 93 94]
  [ 5  0  3  2]]]
[[[ 5  0  3  2]
  [90 91 93 94]
  [ 0  1  3  4]
  [ 1  2  3  4]]]


In [ ]:
#Write a NumPy program to create a three-dimension array with shape (3,5,4) and set to a variable.

In [7]:
import numpy as np  
numbers = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 2, 1, 3],
               [7, 3, 4, 0],
               [2, 0, 3, 0]],
              
              [[2, 2, 3, 1],
               [4, 0, 0, 5],
               [6, 3, 2, 1],
               [5, 1, 0, 0],               
               [0, 1, 9, 1]],
              
              [[3, 1, 4, 2],
               [4, 1, 6, 0],
               [1, 2, 0, 6],
               [8, 3, 4, 0],               
               [2, 0, 2, 8]]]) 
print("Array:")
print(numbers)

Array:
[[[1 2 3 4]
  [5 6 7 8]
  [9 2 1 3]
  [7 3 4 0]
  [2 0 3 0]]

 [[2 2 3 1]
  [4 0 0 5]
  [6 3 2 1]
  [5 1 0 0]
  [0 1 9 1]]

 [[3 1 4 2]
  [4 1 6 0]
  [1 2 0 6]
  [8 3 4 0]
  [2 0 2 8]]]


In [8]:
#Write a NumPy program to multiply two given arrays of same size element-by-element.

In [9]:
import numpy as np 
nums1 = np.array([[2, 2, 1],
               [4, 0, 0]])
nums2 = np.array([[8, 9, 1],
              [3, 2, 4]])

print("\nMultiply said arrays of same size element-by-element:", np.multiply(nums1, nums2))


Multiply said arrays of same size element-by-element: [[16 18  1]
 [12  0  0]]


In [10]:
#Write a NumPy program to test element-wise for NaN of a given array.

In [13]:
import numpy as np
a = np.array([1, 0, np.nan])
print("Test element-wise for NaN:")
print(np.isnan(a))

Test element-wise for NaN:
[False False  True]


In [17]:
#Write a NumPy program to test element-wise for positive or negative infinity.

In [18]:
import numpy as np
a = np.array([1, 0, np.nan, np.inf])
print("Original array")
print(a)
print("Test element-wise for positive or negative infinity:")
print(np.isinf(a))

Original array
[ 1.  0. nan inf]
Test element-wise for positive or negative infinity:
[False False False  True]


In [19]:
#Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).

In [20]:
import numpy as np
a = np.array([1, 0, np.nan, np.inf])
print("Original array")
print(a)
print("Test a given array element-wise for finiteness :")
print(np.isfinite(a))

Original array
[ 1.  0. nan inf]
Test a given array element-wise for finiteness :
[ True  True False False]


In [21]:
#Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [22]:
import numpy as np
x = np.array([1, 0, 0, 0])
print("Original array:")
print(x)
print("Test whether any of the elements of a given array is non-zero:")
print(np.any(x))
x = np.array([0, 0, 0, 0])
print("Original array:")
print(x)
print("Test whether any of the elements of a given array is non-zero:")
print(np.any(x))

Original array:
[1 0 0 0]
Test whether any of the elements of a given array is non-zero:
True
Original array:
[0 0 0 0]
Test whether any of the elements of a given array is non-zero:
False


In [23]:
#Write a NumPy program to test whether none of the elements of a given array is zero.

In [24]:
import numpy as np
x = np.array([1, 2, 3, 4])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))
x = np.array([0, 1, 2, 3])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))

Original array:
[1 2 3 4]
Test if none of the elements of the said array is zero:
True
Original array:
[0 1 2 3]
Test if none of the elements of the said array is zero:
False


In [25]:
#Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.

In [29]:
l = [11, 12 , 13, 14]
array1 = np.array(l)
print(array1)
type(array1)

[11 12 13 14]


numpy.ndarray

In [28]:
#Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [30]:
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [31]:
#Write a NumPy program to create a null vector of size 10 and update sixth value to 11

In [32]:
import numpy as np
x = np.zeros(10)
print(x)
print("Update sixth value to 11")
x[6] = 11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [33]:
#Write a NumPy program to create an array with values ranging from 12 to 38.

In [35]:
x = np.arange(12, 38)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [36]:
#Write a NumPy program to reverse an array (first element becomes last).

In [37]:
x = x[::-1]
print(x)

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [ ]:
#Write a NumPy program to convert an array to a float type

In [46]:
a = np.array([1,9, 2, 3, 4])
print("Original array")
print(a)
a = a.astype(float)
print(a.dtype)
print(a)


Original array
[1 9 2 3 4]
float64
[1. 9. 2. 3. 4.]


'x = np.asfarray(a)\nprint("Array converted to a float type:")\nprint(x)'

In [51]:
#another way 
a = np.array([1,9, 2, 3, 4])
print("Original array")
print(a)
x = np.asfarray(a)
print("Array converted to a float type:")
print(x)

Original array
[1 9 2 3 4]
Array converted to a float type:
[1. 9. 2. 3. 4.]


In [ ]:
# Write a NumPy program to create a 2d array with 1 on the border and 0 inside.

In [52]:
import numpy as np
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)


Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#Write a NumPy program to add a border (filled with 0's) around an existing array.

In [53]:
import numpy as np
x = np.ones((3,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [54]:
#Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [61]:
import numpy as np
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [62]:
'''Write a NumPy program to compute the multiplication of two given matrixes.

Sample Matrix:

[[1, 0], [0, 1]]
[[1, 2], [3, 4]]'''

'Write a NumPy program to compute the multiplication of two given matrixes.\n\nSample Matrix:\n\n[[1, 0], [0, 1]]\n[[1, 2], [3, 4]]'

In [64]:
import numpy as np
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
result1 = np.dot(p, q)
print("Result of the said matrix multiplication:")
print(result1)

Result of the said matrix multiplication:
[[1 2]
 [3 4]]


In [65]:
#Write a NumPy program to compute the determinant of a given square array.

In [66]:
import numpy as np
a = np.array([[1, 2], [4, 2]])
print("Original 2-d array")
print(a)
print("Determinant of the said 2-D array:")
print(np.linalg.det(a))

Original 2-d array
[[1 2]
 [4 2]]
Determinant of the said 2-D array:
-6.0


In [68]:
#Write a NumPy program to compute the outer product of two given vectors.

In [67]:
result = np.outer(p, q)
print("Outer product of the said two vectors:")
print(result)

Outer product of the said two vectors:
[[1 2 3 4]
 [0 0 0 0]
 [0 0 0 0]
 [1 2 3 4]]


In [69]:
#Write a NumPy program to compute the inverse of a given matrix.

In [71]:
result =  np.linalg.inv(q)
print("Inverse of the said matrix:")
print(result)

Inverse of the said matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [72]:
#Write a NumPy program to compute the sum of the diagonal element of a given array.

In [74]:
arr = np.random.rand(5,5)
result2 =  np.trace(arr)
print("Condition number of the said matrix:")
print(result2)

Condition number of the said matrix:
2.3325922068821336


In [75]:
#Write a NumPy program to check two random arrays are equal or not.

In [76]:
import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[0 1 1 0 0 0]
Second array:
[1 1 1 0 1 0]
Test above two arrays are equal or not!
False


In [81]:
#another way
import numpy as np
x = np.random.rand(1,5)
print("First array:")
print(x)
y = np.random.rand(1,5)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[[0.69557248 0.63757767 0.35405555 0.73381048 0.33761707]]
Second array:
[[0.95407071 0.1117667  0.15024656 0.57539131 0.91530709]]
Test above two arrays are equal or not!
False


In [82]:
#Write a NumPy program to generate five random numbers from the normal distribution.

In [83]:
import numpy as np
x = np.random.normal(size=5)
print(x)

[-0.05648438 -0.57607359 -0.99918594  0.23660841 -0.13632628]


In [84]:
print(np.random.randn(3,3))

[[ 1.53417272  1.75105538 -2.01869068]
 [ 0.06973804  0.52014256  1.94699687]
 [-0.26123986 -0.52373329  0.01228563]]


In [85]:
#Write a NumPy program to generate six random integers between 10 and 30.

In [90]:
print(np.random.randint(10, 30, 6 ))

[19 17 11 12 22 11]


In [91]:
import numpy as np
x = np.random.randint(low=10, high=30, size=6)
print(x)

[25 19 27 11 27 14]


In [92]:
#Write a NumPy program to create a 3x3x3 array with random values.

In [93]:
import numpy as np
arr = np.random.random((3,3,3))
print(arr)

[[[0.67306663 0.65480267 0.13732022]
  [0.15793064 0.3700007  0.17078644]
  [0.18114619 0.01522595 0.40388903]]

 [[0.97849918 0.96227977 0.03361124]
  [0.72199488 0.04135832 0.40254812]
  [0.55239086 0.94452341 0.43638919]]

 [[0.73830945 0.24590284 0.08775508]
  [0.97207182 0.37116282 0.15548805]
  [0.49006384 0.96530867 0.76530632]]]


In [94]:
#Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.

In [95]:
x = np.random.random((5,5))
print(x) 
print("Minimum and Maximum Values:")
print( x.min(), x.max())

[[0.49513316 0.64528099 0.9336088  0.89689097 0.55155248]
 [0.09364048 0.5517106  0.64213677 0.72893918 0.38984169]
 [0.57005247 0.61538564 0.02579274 0.48034103 0.13225498]
 [0.75105756 0.68189772 0.03086397 0.31099662 0.2697993 ]
 [0.44460063 0.11769069 0.21613314 0.04723123 0.35287183]]
Minimum and Maximum Values:
0.02579274209047111 0.9336088026015628


In [96]:
#Write a NumPy program to create a random vector of size 10 and sort it.

In [97]:
import numpy as np
x = np.random.random(10)
print("Original array:", x)
x.sort()
print("Sorted array:", x)


Original array: [0.01101681 0.40219857 0.8046179  0.48993515 0.33816225 0.95680622
 0.11613826 0.47179668 0.50796522 0.9606825 ]
Sorted array: [0.01101681 0.11613826 0.33816225 0.40219857 0.47179668 0.48993515
 0.50796522 0.8046179  0.95680622 0.9606825 ]


In [98]:
#Write a NumPy program to create random vector of size 15 and replace the maximum value by -1.

In [99]:
import numpy as np
x = np.random.random(15)
print("Original array:",x)
x[x.argmax()] = -1
print("Maximum value replaced by -1:")
print(x)

Original array: [0.49954109 0.76880774 0.73200633 0.40584474 0.1920458  0.26085762
 0.63468164 0.25611595 0.69741479 0.13823164 0.35778972 0.47712692
 0.04434376 0.53745214 0.79821337]
Maximum value replaced by -1:
[ 0.49954109  0.76880774  0.73200633  0.40584474  0.1920458   0.26085762
  0.63468164  0.25611595  0.69741479  0.13823164  0.35778972  0.47712692
  0.04434376  0.53745214 -1.        ]


In [100]:
#Write a NumPy program to shuffle numbers between 0 and 10 (inclusive).

In [101]:
import numpy as np
arr = np.arange(10)
np.random.shuffle(arr)
print(arr)

[8 2 0 9 7 4 3 6 5 1]


In [102]:
#Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable.

In [103]:
import numpy as np
x = np.random.rand(10, 4)
print("Original array: ")
print(x)
y= x[:5, :]
print("First 5 rows of the above array:")
print(y)

Original array: 
[[0.94841474 0.91662216 0.52648976 0.70417265]
 [0.70404406 0.9086419  0.06830489 0.65999698]
 [0.28684413 0.71463374 0.75772373 0.02057804]
 [0.43723773 0.33687556 0.49350183 0.68743497]
 [0.16843317 0.6872224  0.96086111 0.00868691]
 [0.96650829 0.16160802 0.7587211  0.09647791]
 [0.50624842 0.35099044 0.66401723 0.80968575]
 [0.42434517 0.81372814 0.9144825  0.94179248]
 [0.85454433 0.64025993 0.78686834 0.9074902 ]
 [0.77817003 0.55203858 0.70108776 0.50744277]]
First 5 rows of the above array:
[[0.94841474 0.91662216 0.52648976 0.70417265]
 [0.70404406 0.9086419  0.06830489 0.65999698]
 [0.28684413 0.71463374 0.75772373 0.02057804]
 [0.43723773 0.33687556 0.49350183 0.68743497]
 [0.16843317 0.6872224  0.96086111 0.00868691]]


In [104]:
#Write a NumPy program to sort the specified number of elements from beginning of a given array.

In [105]:
import numpy as np
nums =  np.random.rand(10)
print("Original array:")
print(nums)
print("\nSorted first 5 elements:")
print(nums[np.argpartition(nums,range(5))])

Original array:
[0.39584259 0.48605208 0.7234843  0.39559642 0.7616823  0.92163935
 0.11944803 0.80537934 0.90875593 0.3056832 ]

Sorted first 5 elements:
[0.11944803 0.3056832  0.39559642 0.39584259 0.48605208 0.92163935
 0.7234843  0.80537934 0.90875593 0.7616823 ]


In [106]:
print(np.sort(nums, axis=0))   

[0.11944803 0.3056832  0.39559642 0.39584259 0.48605208 0.7234843
 0.7616823  0.80537934 0.90875593 0.92163935]


In [107]:
#Write a NumPy program to get the indices of the sorted elements of a given array.

In [108]:
x = np.sort(nums)
print(x)

[0.11944803 0.3056832  0.39559642 0.39584259 0.48605208 0.7234843
 0.7616823  0.80537934 0.90875593 0.92163935]


In [109]:
#another way
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
print("Original array:")
print(student_id)
i = np.argsort(student_id)
print("Indices of the sorted elements of a given array:")
print(i)

Original array:
[1023 5202 6230 1671 1682 5241 4532]
Indices of the sorted elements of a given array:
[0 3 4 6 1 5 2]


In [110]:
#Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort by class, then height if class are equal.

In [111]:
import numpy as np
data_type = [('name', 'S15'), ('class', int), ('height', float)]
students_details = [('James', 5, 48.5), ('Nail', 6, 52.5),('Paul', 5, 42.10), ('Pit', 5, 40.11)]
# create a structured array
students = np.array(students_details, dtype=data_type)   
print("Original array:")
print(students)
print("Sort by class, then height if class are equal:")
print(np.sort(students, order=['class', 'height']))

Original array:
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
 (b'Pit', 5, 40.11)]
Sort by class, then height if class are equal:
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


In [112]:
#Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort the array on height.

In [113]:
print(np.sort(students, order='height'))    


[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


In [114]:
#Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array.

In [115]:
import numpy as np
a = np.array([[10,40],[30,20]])
print("Original array:")
print(a)
print("Sort the array along the first axis:")
print(np.sort(a, axis=0))
print("Sort the array along the last axis:")
print(np.sort(a))
print("Sort the flattened array:")
print(np.sort(a, axis=None))

Original array:
[[10 40]
 [30 20]]
Sort the array along the first axis:
[[10 20]
 [30 40]]
Sort the array along the last axis:
[[10 40]
 [20 30]]
Sort the flattened array:
[10 20 30 40]


In [117]:
#Write a NumPy program to generate a matrix product of two arrays.

In [118]:
import numpy as np
x = [[1, 0], [1, 1]]
y = [[3, 1], [2, 2]]
print("Matrices and vectors.")
print("x:")
print(x)
print("y:")
print(y)
print("Matrix product of above two arrays:")
print(np.matmul(x, y))


Matrices and vectors.
x:
[[1, 0], [1, 1]]
y:
[[3, 1], [2, 2]]
Matrix product of above two arrays:
[[3 1]
 [5 3]]


In [120]:
#Write a NumPy program to multiply a 5x3 matrix by a 3x2 matrix and create a real matrix product.

In [121]:
import numpy as np
x = np.random.random((5,3))
print("First array:")
print(x)
y = np.random.random((3,2))
print("Second array:")
print(y)
z = np.dot(x, y)
print("Dot product of two arrays:")
print(z)

First array:
[[0.97484938 0.50626487 0.85259318]
 [0.03051343 0.1183377  0.81512726]
 [0.96121211 0.44508308 0.83628771]
 [0.58862266 0.26998263 0.72887719]
 [0.63451483 0.8881228  0.41088742]]
Second array:
[[0.58078911 0.81195211]
 [0.07446087 0.40344348]
 [0.92840098 0.98852474]]
Dot product of two arrays:
[[1.39542716 1.83858972]
 [0.78329834 0.87829148]
 [1.36781312 1.78671515]
 [1.03865907 1.30736928]
 [0.81611798 1.27967539]]


In [122]:
#Write a NumPy program to calculate the absolute value element-wise.

In [125]:
x = np.array([-10.2, 122.2, .20])
print("Original array:")
print(x)
print("Element-wise absolute value:")
print(np.abs(x))
print(np.absolute(x))

Original array:
[-10.2 122.2   0.2]
Element-wise absolute value:
[ 10.2 122.2   0.2]
[ 10.2 122.2   0.2]


In [126]:
#Write a NumPy program to get the element-wise remainder of an array of division.

In [127]:
import numpy as np
x = np.arange(7)
print("Original array:")
print(x)
print("Element-wise remainder of division:")
print(np.remainder(x, 5))

Original array:
[0 1 2 3 4 5 6]
Element-wise remainder of division:
[0 1 2 3 4 0 1]


In [128]:
#Write a NumPy program to get the powers of an array values element-wise.

In [129]:
import numpy as np
x = np.arange(7)
print("Original array")
print(x)
print("First array elements raised to powers from second array, element-wise:")
print(np.power(x, 3))

Original array
[0 1 2 3 4 5 6]
First array elements raised to powers from second array, element-wise:
[  0   1   8  27  64 125 216]


In [130]:
#Write a NumPy program to get the largest integer smaller or equal to the division of the inputs.

In [131]:
x = [1., 2., 3., 4.]
print("Original array:")
print(x)
print("Largest integer smaller or equal to the division of the inputs:")
print(np.floor_divide(x, 1.5))

Original array:
[1.0, 2.0, 3.0, 4.0]
Largest integer smaller or equal to the division of the inputs:
[0. 1. 2. 2.]


In [132]:
#Write a NumPy program to add, subtract, multiply, divide arguments element-wise.
#Sample elements: 4.0, 1.2

In [133]:
import numpy as np
print("Add:")
print(np.add(1.0, 4.0))
print("Subtract:")
print(np.subtract(1.0, 4.0))
print("Multiply:")
print(np.multiply(1.0, 4.0))
print("Divide:")
print(np.divide(1.0, 4.0))


Add:
5.0
Subtract:
-3.0
Multiply:
4.0
Divide:
0.25


In [139]:
#Write a NumPy program to get the dates of yesterday, today and tomorrow.

In [134]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2022-11-01
Today:  2022-11-02
Tomorrow:  2022-11-03


In [138]:
#Write a NumPy program to count the number of days of specific month.

In [135]:
import numpy as np
print("Number of days, February, 2016: ")
print(np.datetime64('2016-03-01') - np.datetime64('2016-02-01'))
print("Number of days, February, 2017: ")
print(np.datetime64('2017-03-01') - np.datetime64('2017-02-01'))
print("Number of days, February, 2018: ")
print(np.datetime64('2018-03-01') - np.datetime64('2018-02-01'))

Number of days, February, 2016: 
29 days
Number of days, February, 2017: 
28 days
Number of days, February, 2018: 
28 days


In [137]:
#Write a NumPy program to display all the dates for the month of March, 2017.

In [136]:
import numpy as np
print("March, 2017")
print(np.arange('2017-03', '2017-04', dtype='datetime64[D]'))

March, 2017
['2017-03-01' '2017-03-02' '2017-03-03' '2017-03-04' '2017-03-05'
 '2017-03-06' '2017-03-07' '2017-03-08' '2017-03-09' '2017-03-10'
 '2017-03-11' '2017-03-12' '2017-03-13' '2017-03-14' '2017-03-15'
 '2017-03-16' '2017-03-17' '2017-03-18' '2017-03-19' '2017-03-20'
 '2017-03-21' '2017-03-22' '2017-03-23' '2017-03-24' '2017-03-25'
 '2017-03-26' '2017-03-27' '2017-03-28' '2017-03-29' '2017-03-30'
 '2017-03-31']


In [143]:
#Write a NumPy program to get the minimum and maximum value of a given array along the second axis.

In [144]:
import numpy as np
x = np.arange(4).reshape((2, 2))
print("\nOriginal array:")
print(x)
print("\nMaximum value along the second axis:")
print(np.amax(x, 1))
print("Minimum value along the second axis:")
print(np.amin(x, 1))


Original array:
[[0 1]
 [2 3]]

Maximum value along the second axis:
[1 3]
Minimum value along the second axis:
[0 2]


In [145]:
#Write a Python program to find the maximum and minimum value of a given flattened array.

In [146]:
print(np.amax(x))
print(np.amin(x))

3
0


In [157]:
#Write a NumPy program to replace "PHP" with "Python" in the element of a given array.

In [159]:
import numpy as np
x = np.array(['PHP Exercises, Practice, Solution'], dtype=np.str)
print("\nOriginal Array:")
print(x)
x[0]='Python Exercises'
r = np.char.replace(x, "PHP", "Python")
print("\nNew array:")
print(r)
print(x)


Original Array:
['PHP Exercises, Practice, Solution']

New array:
['Python Exercises']
['Python Exercises']


C:\Users\hp\AppData\Local\Temp\ipykernel_17284\3696213087.py:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array(['PHP Exercises, Practice, Solution'], dtype=np.str)


In [160]:
#Write a NumPy program to make all the elements of a given string to a numeric string of 5 digits with zeros on its left.

In [161]:
import numpy as np
x = np.array(['2', '11', '234', '1234', '12345'], dtype=np.str)
print("\nOriginal Array:")
print(x)
r = np.char.zfill(x, 5)
print("\nNumeric string of 5 digits with zeros:")
print(r) 


Original Array:
['2' '11' '234' '1234' '12345']

Numeric string of 5 digits with zeros:
['00002' '00011' '00234' '01234' '12345']


C:\Users\hp\AppData\Local\Temp\ipykernel_17284\3527862124.py:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array(['2', '11', '234', '1234', '12345'], dtype=np.str)


In [162]:
#Write a NumPy program to split the element of a given array with spaces.

In [164]:
x = np.array(['Python PHP Java C++'], dtype=np.str)
r = np.char.split(x)
print(r)

[list(['Python', 'PHP', 'Java', 'C++'])]


C:\Users\hp\AppData\Local\Temp\ipykernel_17284\1864747382.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array(['Python PHP Java C++'], dtype=np.str)


In [165]:
#Write a NumPy program to insert a space between characters of all the elements of a given array.

In [166]:
import numpy as np
x = np.array(['python exercises', 'PHP', 'java', 'C++'], dtype=np.str)
print("Original Array:")
print(x)
r = np.char.join(" ", x)
print(r)

Original Array:
['python exercises' 'PHP' 'java' 'C++']
['p y t h o n   e x e r c i s e s' 'P H P' 'j a v a' 'C + +']


C:\Users\hp\AppData\Local\Temp\ipykernel_17284\466967180.py:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array(['python exercises', 'PHP', 'java', 'C++'], dtype=np.str)


In [167]:
#Write a NumPy program to make the length of each element 15 of a given array and the string centered / left-justified / right-justified with paddings of _.

In [168]:
centered = np.char.center(x, 15, fillchar='_')
left = np.char.ljust(x, 15, fillchar='_')
right = np.char.rjust(x, 15, fillchar='_')
print("\nCentered =", centered)
print("Left =", left)
print("Right =", right)



Centered = ['python exercise' '______PHP______' '______java_____' '______C++______']
Left = ['python exercise' 'PHP____________' 'java___________' 'C++____________']
Right = ['python exercise' '____________PHP' '___________java' '____________C++']


In [169]:
#Write a NumPy program to repeat all the elements three times of a given array of string.

In [170]:
x1 = np.array(['Python', 'PHP', 'Java', 'C++'], dtype=np.str)
print("Original Array:")
print(x1)
new_array = np.char.multiply(x1, 3)
print("New array:")
print(new_array)

Original Array:
['Python' 'PHP' 'Java' 'C++']
New array:
['PythonPythonPython' 'PHPPHPPHP' 'JavaJavaJava' 'C++C++C++']


C:\Users\hp\AppData\Local\Temp\ipykernel_17284\3340946343.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x1 = np.array(['Python', 'PHP', 'Java', 'C++'], dtype=np.str)


In [171]:
#Write a NumPy program to concatenate element-wise two arrays of string.

In [172]:
x1 = np.array(['Python', 'PHP'], dtype=np.str)
x2 = np.array([' Java', ' C++'], dtype=np.str)
print("Array1:")
print(x1)
print("Array2:")
print(x2)
new_array = np.char.add(x1, x2)
print("new array:")
print(new_array)

Array1:
['Python' 'PHP']
Array2:
[' Java' ' C++']
new array:
['Python Java' 'PHP C++']


C:\Users\hp\AppData\Local\Temp\ipykernel_17284\786484395.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x1 = np.array(['Python', 'PHP'], dtype=np.str)
C:\Users\hp\AppData\Local\Temp\ipykernel_17284\786484395.py:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x2 = np.array([' Java', ' C++'], dtype=np.str)
