# semi-supervised learning

In [ ]:
What is Semi-supervised Learning?
Semi-supervised learning is a broad category of machine learning techniques that utilizes both labeled and unlabeled data; 
in this way, as the name suggests, it is a hybrid technique between supervised and unsupervised learning.
In general, the core idea of semi-supervision is to treat a datapoint differently based on whether it has a label or not:
    for labeled points, the algorithm will use traditional supervision to update the model weights; and for unlabeled points,
    the algorithm minimizes the difference in predictions between other similar training examples.

# non statistical model

In [ ]:
Non-statistical sampling is the selection of a test group that is based on the examiner's judgment,
rather than a formal statistical method. For example, an examiner could use his own judgment to determine one or more of
the following:

*The sample size
*The items selected for the test group
*How the results are evaluated

It can make sense to use non-statistical sampling when the population size is very small. In this case, it is not efficient to 
spend the extra time to set up a statistical sample. This approach is also useful in areas where specific records contain 
sensitive information, and so must be examined. For example, an examiner might want to select the invoices of specific law
firms, because these firms deal with environmental obligations, which may involve substantial liabilities.

# linear regression modeling

In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

Predict canada's per capita income in year 2020. There is an exercise folder here on github at same level as this notebook, 
download that and you will find canada_per_capita_income.csv file. Using this build a regression model and predict the per 
capita income fo canadian citizens in year 2020

In [3]:
df = pd.read_csv('C:/Users/hp/Downloads/notebooks/ML/1_linear_reg/Exercise/canada_per_capita_income.csv')
df

year  per capita income (US$)
0   1970              3399.299037
1   1971              3768.297935
2   1972              4251.175484
3   1973              4804.463248
4   1974              5576.514583
5   1975              5998.144346
6   1976              7062.131392
7   1977              7100.126170
8   1978              7247.967035
9   1979              7602.912681
10  1980              8355.968120
11  1981              9434.390652
12  1982              9619.438377
13  1983             10416.536590
14  1984             10790.328720
15  1985             11018.955850
16  1986             11482.891530
17  1987             12974.806620
18  1988             15080.283450
19  1989             16426.725480
20  1990             16838.673200
21  1991             17266.097690
22  1992             16412.083090
23  1993             15875.586730
24  1994             15755.820270
25  1995             16369.317250
26  1996             16699.826680
27  1997             17310.757750
28  1998             16622.671870
29  1999             17581.024140
30  2000             18987.382410
31  2001             18601.397240
32  2002             19232.175560
33  2003             22739.426280
34  2004             25719.147150
35  2005             29198.055690
36  2006             32738.262900
37  2007             36144.481220
38  2008             37446.486090
39  2009             32755.176820
40  2010             38420.522890
41  2011             42334.711210
42  2012             42665.255970
43  2013             42676.468370
44  2014             41039.893600
45  2015             35175.188980
46  2016             34229.193630

In [8]:
df.columns

Index(['year', 'per capita income (US$)'], dtype='object')

In [9]:
year = df.drop('per capita income (US$)',axis='columns')
year

year
0   1970
1   1971
2   1972
3   1973
4   1974
5   1975
6   1976
7   1977
8   1978
9   1979
10  1980
11  1981
12  1982
13  1983
14  1984
15  1985
16  1986
17  1987
18  1988
19  1989
20  1990
21  1991
22  1992
23  1993
24  1994
25  1995
26  1996
27  1997
28  1998
29  1999
30  2000
31  2001
32  2002
33  2003
34  2004
35  2005
36  2006
37  2007
38  2008
39  2009
40  2010
41  2011
42  2012
43  2013
44  2014
45  2015
46  2016

In [11]:
price = df["per capita income (US$)"]
price

0      3399.299037
1      3768.297935
2      4251.175484
3      4804.463248
4      5576.514583
5      5998.144346
6      7062.131392
7      7100.126170
8      7247.967035
9      7602.912681
10     8355.968120
11     9434.390652
12     9619.438377
13    10416.536590
14    10790.328720
15    11018.955850
16    11482.891530
17    12974.806620
18    15080.283450
19    16426.725480
20    16838.673200
21    17266.097690
22    16412.083090
23    15875.586730
24    15755.820270
25    16369.317250
26    16699.826680
27    17310.757750
28    16622.671870
29    17581.024140
30    18987.382410
31    18601.397240
32    19232.175560
33    22739.426280
34    25719.147150
35    29198.055690
36    32738.262900
37    36144.481220
38    37446.486090
39    32755.176820
40    38420.522890
41    42334.711210
42    42665.255970
43    42676.468370
44    41039.893600
45    35175.188980
46    34229.193630
Name: per capita income (US$), dtype: float64

In [12]:
# Create linear regression object
reg = linear_model.LinearRegression() 
reg.fit(year,price) 

LinearRegression()

In [13]:
reg.predict([[2020]])

C:\Users\hp\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([41288.69409442])

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

# Linear Regression Multiple Variables

In exercise folder (same level as this notebook on github) there is hiring.csv. This file contains hiring statics for a firm 
such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide 
the salary. Given this data, you need to build a machine learning model for HR department that can help them decide salaries 
for future candidates. Using this predict salaries for following candidates,

**2 yr experience, 9 test score, 6 interview score**

**12 yr experience, 10 test score, 10 interview score**

In [15]:
data = pd.read_csv('C:/Users/hp/Downloads/notebooks/ML/2_linear_reg_multivariate/Exercise/hiring.csv')
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [17]:
data.columns

Index(['experience', 'test_score(out of 10)', 'interview_score(out of 10)',
       'salary($)'],
      dtype='object')

In [20]:
data.fillna({
        'experience': "two",
        'test_score(out of 10)': 6.0
    }, inplace= True)
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        two                    8.0                           9      50000
1        two                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    6.0                           7      72000
7     eleven                    7.0                           8      80000

In [23]:
!pip install word2number

  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5583 sha256=c1445c4b8b19a6ecf715eb442b2d34ae3ab1028d96293f4968ec277c71cc742a
  Stored in directory: c:\users\hp\appdata\local\pip\cache\wheels\a0\4a\5b\d2f2df5c344ddbecb8bea759872c207ea91d93f57fb54e816e
Successfully built word2number


In [24]:
from word2number import w2n
data.experience = data.experience.apply(w2n.word_to_num)
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           2                    8.0                           9      50000
1           2                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    6.0                           7      72000
7          11                    7.0                           8      80000

In [25]:
x = data.drop('salary($)',axis='columns')
y = data["salary($)"]

In [26]:
x

experience  test_score(out of 10)  interview_score(out of 10)
0           2                    8.0                           9
1           2                    8.0                           6
2           5                    6.0                           7
3           2                   10.0                          10
4           7                    9.0                           6
5           3                    7.0                          10
6          10                    6.0                           7
7          11                    7.0                           8

In [27]:
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary($), dtype: int64

In [31]:
model = linear_model.LinearRegression()
model.fit(x,y)

LinearRegression()

In [32]:
model.predict([[2,9,6]])

C:\Users\hp\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([49830.62338753])

In [33]:
model.predict([[12,10,10]])

C:\Users\hp\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([98187.97624048])